---
- name: Ensure basic packages are installed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - cron
      - screen
      - vim
      - curl
      - wget
      - rsync
      - python-apt
      - python-pip
      - software-properties-common
  become: yes

- name: Ensure timezone is set
  timezone:
    name: "{{ BASELINE_TIMEZONE_LINUX }}"

