---
- include: windows.yml
  when: "'windows' in group_names or 'os_windows' in group_names"
  tags:
    - common

- include: linux.yml
  when: "'linux' in group_names"
  become: yes
  tags:
    - common
