---
- name: Ensure chocolatey is installed
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  args:
    creates: C:\ProgramData\chocolatey\choco.exe

- name: Ensure timezone is set
  win_timezone:
    timezone: "{{ BASELINE_TIMEZONE_WINDOWS }}"
